### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kminov** [tzyganu/rule-products#1]
Hi, 

I just installed the module the way u prescribed, but I get this error:

Fatal error: Class 'Easylife_RuleProducts_Model_Resource_Setup' not found in /.../includes/src/Mage_Core_Model_Resource_Setup.php on line 234

I am using 1.9

**Comment by tzyganu** [comment]
it looks like you have the compiler enabled. You should never install extensions with the compiler enabled. Disable it, install the extension then enable it again.  
To make it clear the class is there: https://github.com/tzyganu/rule-products/blob/master/app/code/community/Easylife/RuleProducts/Model/Resource/Setup.php. Let me know if it works after you disable the compiler.

**Comment by kminov** [comment]
You are right, it was ON. I disabled the compiler and everything's working. As soon as I get it back ON it crashes with that error again. Perhaps I should leave it off anyway?

**Comment by tzyganu** [comment]
@kminov I usually work with the compiler off. Maybe you need to configure it to include this extension as well.  
I will close the issue for now since the problem seams to be solved.
