### ISSUE TITLE
sitemap.xml

### ISSUE THREAD

**Issue by shahroq** [tzyganu/rule-products#2]
hello,
just tested the add-on, one thing that i noticed is that product rule url does not includes at the magento generated sitemap.xml ? is it right? if so, is there any way to include these at the sitemap.xml?

**Comment by tzyganu** [comment]
@shahroq This is not in the scope of the extension. If you want you can include the links in the sitemap by rewriting the [`generateXml` method in the sitemap model](https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Sitemap/Model/Sitemap.php#L130).  
Follow the same guidelines as for the products and categories (mostly categories).
