### ISSUE TITLE
Use utf8 characters as url key

### ISSUE THREAD

**Issue by shahroq** [tzyganu/rule-products#3]
Hi,
For supporting utf-8 character as url key at product section, cms,.. i use 
this [this](http://killerwhalesoft.com/blog/magento-unicode-url-key-products-categories-cms-pages/) tutorial and it works great.
For using utf-8 characters as url key at this extension i changed these 2 files: \app\code\community\Easylife\RuleProducts\Model\Ruleproduct\Attribute\Backend\UrlKey.php: formatUrlKey($str)
\app\code\community\Easylife\RuleProducts\Model\Resource\Ruleproduct.php
but still magento remove non utf-8 characters (also all latin chars after that) before saving to database.
Also i changed the value at the easylife_ruleproducts_ruleproduct_varchar.value directly via phpMyAdmin and know it works:
http://mystore.com/coûte
But again going to dashboard and saving entry, saves url key as 'co'
Any idea what file responsible for omitting non utf-8 characters?

**Comment by tzyganu** [comment]
@shahroq  This is not in the scope of the extension. It should work as it works for products and categories. But if you are willing to do a PR with the code that supports utf8 chars, I'm willing to include it in the extension. 
I will close this for now and reopen it if you provide a PR.
