### ISSUE TITLE
Default sorting products

### ISSUE THREAD

**Issue by shahroq** [tzyganu/rule-products#4]
Hello,
Is there a way to custom sort included products?

**Comment by tzyganu** [comment]
@shahroq By default there is no way, but you can edit [this method](https://github.com/tzyganu/rule-products/blob/master/app/code/community/Easylife/RuleProducts/Block/Product/List.php#L40) or [this one](https://github.com/tzyganu/rule-products/blob/master/app/code/community/Easylife/RuleProducts/Model/Layer.php#L61) and apply a sorting to the collection.
